name: Sheet (private) -> PNG -> SeaTalk

on:
  schedule:
    - cron: "0 1 * * *"  # 01:00 UTC ~ 08:00 VN
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Cài poppler để convert PDF -> PNG
      - name: Install poppler (pdftoppm)
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils

      # Cài google-auth-library
      - run: npm init -y
      - run: npm i google-auth-library

      # Debug: in ra file trong workspace để chắc chắn export_and_send.js tồn tại
      - name: Show workspace files
        run: ls -R .

      # Run script chính
      - name: Export PDF -> PNG -> SeaTalk
        run: node export_and_send.js
        env:
          SA_JSON_BASE64: ${{ secrets.SA_JSON_BASE64 }}
          SHEET_ID:       ${{ secrets.SHEET_ID }}
          GID:            ${{ secrets.GID }}
          RANGE_A1:       ${{ secrets.RANGE_A1 }}
          SEA_URL:        ${{ secrets.SEA_URL }}
